Feature/shelly
innovatrics/sf-helm pull request #23
Opened 2024-07-12 11:59 UTC by marek-nereca

2024-07-12 13:39 UTC, Temppus approved these changes

2024-07-12 13:39 UTC, Temppus commented on values.yaml
> +  # -- Annotations for edgeStreamProcessor deployment
update probably forgotten copy pasta comments ?

2024-07-15 04:56 UTC, FooRider requested changes

2024-07-15 04:56 UTC, FooRider commented on templates/edge-streams/relay-controller-deployment.yaml
> +  selector:
I think including possibility of setting `revisionHistoryLimit` and `updateStrategy` is in order.
It was added in recent PR by Egid https://github.com/innovatrics/sf-helm/pull/18/files

2024-08-15 16:24 UTC, merged